#!/bin/sh

SOURCES=$1
SPECFILE=$2
PKGRELEASE=$3
RPMVERSION=$4
SPECRELEASE=$5

test -n "$SPECFILE" &&
        sed -i.bak -e "
	s/%%RPMVERSION%%/$RPMVERSION/
	s/%%PKGRELEASE%%/$PKGRELEASE/
	s/%%SPECRELEASE%%/$SPECRELEASE/" $SPECFILE
rm -f $SPECFILE.bak
