flags = [
  '-I/usr/local/ulibvirt-3.9.0',
  '-I/usr/local/ulibvirt-3.9.0',
  '-I/usr/local/ulibvirt-3.9.0/gnulib/lib',
  '-I/usr/local/ulibvirt-3.9.0/gnulib/lib',
  '-I/usr/local/ulibvirt-3.9.0/include',
  '-I/usr/local/ulibvirt-3.9.0/include',
  '-I/usr/local/ulibvirt-3.9.0/src',
  '-I/usr/local/ulibvirt-3.9.0/src',
  '-I/usr/local/ulibvirt-3.9.0/src/access',
  '-I/usr/local/ulibvirt-3.9.0/src/access',
  '-I/usr/local/ulibvirt-3.9.0/src/admin',
  '-I/usr/local/ulibvirt-3.9.0/src/admin',
  '-I/usr/local/ulibvirt-3.9.0/src/bhyve',
  '-I/usr/local/ulibvirt-3.9.0/src/bhyve',
  '-I/usr/local/ulibvirt-3.9.0/src/conf',
  '-I/usr/local/ulibvirt-3.9.0/src/conf',
  '-I/usr/local/ulibvirt-3.9.0/src/libxl',
  '-I/usr/local/ulibvirt-3.9.0/src/libxl',
  '-I/usr/local/ulibvirt-3.9.0/src/locking',
  '-I/usr/local/ulibvirt-3.9.0/src/locking',
  '-I/usr/local/ulibvirt-3.9.0/src/logging',
  '-I/usr/local/ulibvirt-3.9.0/src/logging',
  '-I/usr/local/ulibvirt-3.9.0/src/lxc',
  '-I/usr/local/ulibvirt-3.9.0/src/lxc',
  '-I/usr/local/ulibvirt-3.9.0/src/qemu',
  '-I/usr/local/ulibvirt-3.9.0/src/qemu',
  '-I/usr/local/ulibvirt-3.9.0/src/remote',
  '-I/usr/local/ulibvirt-3.9.0/src/remote',
  '-I/usr/local/ulibvirt-3.9.0/src/rpc',
  '-I/usr/local/ulibvirt-3.9.0/src/rpc',
  '-I/usr/local/ulibvirt-3.9.0/src/secret',
  '-I/usr/local/ulibvirt-3.9.0/src/secret',
  '-I/usr/local/ulibvirt-3.9.0/src/security',
  '-I/usr/local/ulibvirt-3.9.0/src/security',
  '-I/usr/local/ulibvirt-3.9.0/src/util',
  '-I/usr/local/ulibvirt-3.9.0/src/util',
  '-I/usr/local/ulibvirt-3.9.0/src/vmx',
  '-I/usr/local/ulibvirt-3.9.0/src/vmx',
  '-I/usr/local/ulibvirt-3.9.0/src/xenconfig',
  '-I/usr/local/ulibvirt-3.9.0/src/xenconfig',
]

def FlagsForFile(filename, **kwargs):
  return { 'flags': flags, 'do_cache': True }
